services:

  postgres:
    image: postgres:16-alpine
    container_name: cloud_postgres_dev
    restart: unless-stopped
    networks:
      - cloud_network
    environment:
      POSTGRES_DB: my_cloud_storage_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./MyCloudStorage
      dockerfile: Dockerfile
    container_name: cloud_backend_dev
    ports:
      - "5000:8080"
    restart: unless-stopped
    networks:
      - cloud_network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Production
      - JWT_KEY=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - DB_PASSWORD=${DB_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_KEY=${SMTP_KEY}
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=my_cloud_storage_db;Username=postgres;Password=${DB_PASSWORD}
    volumes:
      - ./uploads_dev:/app/uploads

  frontend:
    build:
      context: ../MyCloudStorageFrontend/file-manager
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=/api
    container_name: cloud_frontend_dev
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - cloud_network
    depends_on:
      - api

networks:
  cloud_network:
    driver: bridge

volumes:
  postgres_dev_data: